### ISSUE TITLE
It makes formControl dirty.

### ISSUE THREAD

**Issue by Vinay-Kr-Verma** [manishjanky/ngx-select-dropdown#179] opened 2020-05-30 16:39 UTC
When I set value programmatically by using setValue() or patchValue() functions it makes the formControl dirty. So I am not able to check whether form is changed or not.

**Comment by manishjanky** [comment] 2020-06-02 04:59
Can you please create a demo replicating the issue on stackblitz and point out the exact issue you face.

**Comment by Vinay-Kr-Verma** [comment] 2020-06-05 01:33
please find here https://stackblitz.com/edit/angular-gitter-p13tng

**Comment by manishjanky** [comment] 2020-06-07 16:58
@Vinay-Kr-Verma  this is really strange. As I'm not setting this from within the component.. And angular docs say when the value is changed programatically the control will not be marked dirty.
Give me some time to look into this..

**Comment by micah-akpan** [comment] 2020-08-28 08:32
@manishjanky Please can you point me to the place in docs that says the control will not be marked dirty when it's value is changed programmatically

**Comment by nehal076** [comment] 2020-09-15 06:47
Hey @manishjanky, any update on this issue?

**Comment by Vinay-Kr-Verma** [comment] 2020-09-15 06:58
@manishjanky hey how can you close the issue without fixing it. It's expected behaviour of any input component check other dropdown components available there

**Comment by nehal076** [comment] 2020-09-15 07:31
For anyone looking for a solution to this, you can use `markAsPristine()` or `markAsUntouched()` whenever you use` setValue()` or `patchValue()` programmatically, to avoid this issue.

**Comment by manishjanky** [comment] 2021-01-22 18:31
@Vinay-Kr-Verma I think you can be a bit more respectful. I closed the other issue which was a duplicate of this one. This issue is still open.

**Comment by manishjanky** [comment] 2021-01-22 18:35
@micah-akpan i dont have the reference on hand. But here is a github issue raised on angular repository. As per the comments on the thread this problem exists in Angular 7 as well.

https://github.com/angular/angular/issues/9768

Hope this helps :)

**Closed by manishjanky** 2021-01-22 18:35 UTC

**Comment by nehal076** [comment] 2021-01-25 05:17
> please find here https://stackblitz.com/edit/angular-gitter-p13tng

`this.ngxForm.controls.color.markAsPristine(); `
Add this line after setValue
