### ISSUE TITLE
Cannot change the value through ts code.

### ISSUE THREAD

**Issue by tarun04** [manishjanky/ngx-select-dropdown#92] opened 2019-02-01 15:00 UTC
Angular 2+
.html
[(ngModel)]=''component.value"

.ts 
component.value = ''some new value''

Doesn't work as expected. Am I configuring something wrong on the html?

**Comment by juhana** [comment] 2019-07-19 10:18
This is the only way I could get it working. You need to reset the options list after setting the value to force the component to refresh.

```
<ngx-select-dropdown [(ngModel)]="component.value" [options]="options">

this.component.value = "some new value";
setTimeout(() => this.options = [...this.options], 1);
```

**Comment by manishjanky** [comment] 2019-08-29 07:55
Duplicate of #95

**Closed by manishjanky** 2019-08-29 07:55 UTC
