### ISSUE TITLE
LimitTo does not work for dynamic list

### ISSUE THREAD

**Issue by suryaallampalli** [manishjanky/ngx-select-dropdown#178] opened 2020-05-09 21:30 UTC
Hi,
I have a drop-down list that is populated from an API response and to limit the number of options on the UI, I used 'limitTo' set a number, but I don't see the limitTo attribute in config work as intended,  Is that something I am missing? I have a config variable declared in .ts, 

Please suggest. Thanks

  public configListItems= {
      search : true,
      displayKey : 'description' ,
      height: 'auto',
      limitTo: 4,
}

**Comment by manishjanky** [comment] 2020-05-31 16:58
Which version are you using?
Can you please create a demo replicating the issue..

**Comment by Aprilia1982** [comment] 2020-06-08 07:38
Hi, 
i've got the same issue, also with static items. I'm using the newest version. 

`<ngx-select-dropdown
        [config]="config" 
        [options]="options" 
        [multiple]="false" >
</ngx-select-dropdown>`

`import { ApiResponse } from './../../models/api-response';
import { Wbt } from './../../interfaces/wbt';
import { ApiService } from './../../services/api.service';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-issue-wbt',
  templateUrl: './issue-wbt.component.html',
  styleUrls: ['./issue-wbt.component.scss']
})
export class IssueWbtComponent implements OnInit {

  public options: Wbt[] = [
            {"itmId":10004,"itmItemId":"itmId1","itlTitle":"Title 1"},
            {"itmId":10005,"itmItemId":"itmId2","itlTitle":"Title 2"},
            {"itmId":10004,"itmItemId":"itmId3","itlTitle":"Title 3"},
            {"itmId":10005,"itmItemId":"itmId4","itlTitle":"Title 4"},
            {"itmId":10004,"itmItemId":"itmId5","itlTitle":"Title 5"},
            {"itmId":10005,"itmItemId":"itmId6","itlTitle":"Title 6"},
            {"itmId":10004,"itmItemId":"itmId7","itlTitle":"Title 7"},
            {"itmId":10005,"itmItemId":"itmId8","itlTitle":"Title 8"}
          ];

  config = {
    displayKey: 'itmItemId', // if objects array passed which key to be displayed defaults to description
    search: true, // true/false for the search functionlity defaults to false,
    height: 'auto', // height of the list so that if there are more no of items
    placeholder: 'Bitte das betroffene Training auswählen', // text to be displayed when no item is selected defaults to Select,
    customComparator: () => {}, // a custom function using which user wants to s
    limitTo: 3, // a number thats limits the no of options displayed in the UI similar to angular's limitTo pipe
    moreText: 'more', // text to be displayed whenmore than one items are selected like Option 1 + 5 more
    noResultsFound: 'Kein Ergebnis gefunden!', // text to be displayed when no items are found while searching
    searchPlaceholder: 'Suchen', // label thats displayed in search input,
    searchOnKey: 'itmItemId', // key on which search should be performed this will
    clearOnSelection: false, // clears search criteria when an option is selected if set to true, default is false
    inputDirection: 'ltr', // the direction of the search input can be rtl or ltr(default)
  };

  constructor(private _api: ApiService) { }

  ngOnInit(): void {
   }
}`
![image](https://user-images.githubusercontent.com/4394191/84004341-aef35980-a96b-11ea-83de-d079c9b83535.png)

Thanks for the nice component and for your review.
Jan

**Comment by manishjanky** [comment] 2020-06-14 18:13
@Aprilia1982 let me have a look.. Will get back to you..

**Comment by suryaallampalli** [comment] 2020-06-14 22:08
Sorry for delay in my response @manishjanky, Version-> "ngx-select-dropdown": {
      "version": "1.4.2",
    },
Also, I just used exact the same code from -> https://stackblitz.com/edit/custom-ngx-select-dropdown?file=app%2Fapp.component.ts  
to check if it has to do something with my code on local, but seems to be not working. 

Thanks @Aprilia1982 for the demo and yes it not just dynamic I even saw this for static too.

**Comment by Aprilia1982** [comment] 2020-06-15 06:11
@suryaallampalli: Do you think you will provide a fix?

**Comment by suryaallampalli** [comment] 2020-06-15 12:28
@manishjanky - is working on it

**Comment by manishjanky** [comment] 2020-06-21 03:26
@suryaallampalli, @Aprilia1982 the demo link above works just fine. So if visit this and see the limitTo is a property that needs to be supplied with the config object. And it is supplied the first `n` number of items will only be displayed. 
If the `limitTo` property is not supplied all the items will be visible.

If the the option are available after an api call the also if the limitTo property is supplied only the `n` of items will be visible.

As i can observe it works as intended. With the  `limitTo` its recommended to use the search. As there are more items available and can be filtered using the search filter.
If this does not suits your needs you can fix the height of the dropdown and there will a scroll available with all the items in the view.

* In the demo above the `limitTo `property is commented.

Here is a [demo ](https://stackblitz.com/edit/custom-ngx-select-dropdown-nlzjzi?file=app%2Fapp.component.ts)I created, in which limitTo is set to 5. And the list is populated after 5 seconds (similar to an api response). Now if you see when the options are available to the dropdown only 1st 5 elements are visible and thats intended.

May be i'm missing the exact issues you are facing if you can please elaborate that. If thats not the case it seems to work fine to me.

Closing this as the functionality is working as expected..

**Closed by manishjanky** 2020-06-21 03:26 UTC
