### ISSUE TITLE
clear selected value not working

### ISSUE THREAD

**Issue by bostromFredrik** [manishjanky/ngx-select-dropdown#95] opened 2019-02-16 10:31 UTC
Hi,

I need help with clearing the selected value/option. I have tried all I can think of and all suggestions I can find on google but no luck.

Angular 7.2.0
ngx-select-dropdown 1.0.1
ngx-smart-modal 7.1.1

I have a form (Template driven) inside an ngx-smart-modal and in that form I have three ngx-select-dropdown, one input and one textarea.

I have a ul/li list that populates (ngFor) from an array of objects with properties that I bind to the controls (ngx-select-dropdown, input & textarea) in the form with [(ngModel)] (I have also tried [ngModel] and [value] but it doesn´t work).

So, when I click to edit my first "Entry" in the ul-list the modal (ngx-smart-modal) shows and the controls all have the expected values (from the binded object). When I click close/save on the smart-modal it closes.

Then when I select another Entry in the list the values in the ngx-select-dropdown are still the ones from the last item BUT the input and the textarea have the new objects values as expected.

I have added a "debug button" in the same form to be able to directly clear the values (as in issue #39) but that doesnt work.

I have tried:
- Setting the binded object to empty (object = {} and array=[]) as in issue #39.
- Setting the binded object to object with empty property {"keyword": ""}
- Setting the selected value on the ngx-select-dropdown to empty string
- Reset the form (form.reset()

Nothing works for the ngx-select-dropdown BUT the input and textarea works as expected.

`<div class="form-group">
          <label for="existing-report-keyword">Sökord:</label>
          <ngx-select-dropdown #existingReportKeyword="ngModel" id="existing-report-keyword"
            name="existing-report-keyword" [(ngModel)]="existingEntryData.keywords"
            (change)="existingKeywordSelectionChanged($event)" [multiple]="true" [config]="existingKeywordConfig"
            [options]="systemData.keywords"></ngx-select-dropdown>
        </div>`

The property existingEntryData.keywords is an array of objects like this:
keywords":[{"keyword":"WFALKEMVS018","active":"True"},{"keyword":"WFALKEMVS018","active":true},{"keyword":"WFALKEMVS009","active":true}]

Can you please help me?

Best regards,
Fredrik

**Comment by bostromFredrik** [comment] 2019-02-16 15:52
UPDATE

I have created an isolated app with only a ngx-select-dropdown and two buttons, one for loading data and one for clearing the value. I have tried doing the clear in the same way as in issue #39 and have partially succeded. It clears the selected value but it takes two clicks on the clear button.

Can you please show me the full correct code for clearing the selected value in the dropdown?

**Comment by fabio-percivaldi** [comment] 2019-02-20 17:04
Hi
if this can help i would like to explain my case:
```this.breedingCycleService.breedingCyclesList = [];
    this.breedingCycleService.selectedBreedingCycle = [];
    this.breedingCycleService.selectedBreedingCycle = [...this.breedingCycleService.selectedBreedingCycle];
    this.visitService.visitList = [];
    this.visitService.selectedVisit = [];
    this.visitService.selectedVisit = [...this.visitService.selectedVisit]
    this.prescriptionService.prescriptionList = [];
    this.prescriptionService.selectedPrescription = [];
    this.prescriptionService.selectedPrescription = [...this.prescriptionService.selectedPrescription]; 
```

when i run the function to clear these 3 selected values, i can see some clearing effect only on the first one (selectedBreedingCycle), on the second interaction with this clear function all 3 selected value are correctly cleared.

**Comment by ermarkar** [comment] 2019-04-20 17:07
is this got solved?

**Comment by bostromFredrik** [comment] 2019-04-20 18:37
Nope. I used another select instead.

Skaffa Outlook för Android<https://aka.ms/ghei36>

________________________________

**Comment by manishjanky** [comment] 2019-08-29 07:56
Duplicate of #90

**Closed by manishjanky** 2019-08-29 07:56 UTC
