### ISSUE TITLE
It doesn't work in Safari (mac, ios)

### ISSUE THREAD

**Issue by fpmk** [manishjanky/ngx-select-dropdown#264] opened 2022-08-17 10:50 UTC
#### Bug description
Try to run on safari, you can open dropdown, but can not select any of elements.

#### Expected result

Works properly in safari browser.
#### Actual result

Not works in Safari browser.
#### Steps to reproduce

1. Click to select box
2. Select element

**Comment by manishjanky** [comment] 2022-08-18 08:47
@fpmk  let me have a look.

**Comment by manishjanky** [comment] 2022-08-20 07:24
@finexware those two functions are there for a reason. The problem is not the functions it's the way Safari handles and executes the event chain and propagation.

**Comment by fpmk** [comment] 2022-08-20 07:29
you have document:click instead of blur for example. Maybe we can remove unnecessary methods? What cases it covers?
Also you have click event on element, and also has focus event.

**Comment by manishjanky** [comment] 2022-08-20 07:37
@fpmk Consider more than one instances of the component on the same screen.
When you open one dropdown, and instead of closing it you go and open another and so on, that's a bad user experience, you should not have to manually close all the drowns. So the document click takes care of that, as and when to click on on the document anywhere and not within a particular instance of the component it hides all the other open dropdown. 
Same goes with focus and blur. When you are using a tab to navigate through the form fields and as soon as a particular instance received focus it opens the dropdown and same triggers a blur event for other instances and hides those dropdown.

So removing any of those events handler's is not an option. I have found a solution busy with it hopefully will release a patch soon.

**Comment by fpmk** [comment] 2022-08-20 07:41
> @fpmk Consider more than one instances of the component on the same screen. When you open one dropdown, and instead of closing it you go and open another and so on, that's a bad user experience, you should not have to manually close all the drowns. So the document click takes care of that, as and when you click on the document anywhere and not within a particular instance of the component it hides all the other open dropdown. Same goes with focus and blur. When you are using a tab to navigate through the form fields and as soon as a particular instance received focus it opens the dropdown and same triggers a blur event for other instances and hides those dropdown.
> 
> So removing any of those events handler's is not an option. I have found a solution busy with it hopefully will release a patch soon.

good to hear :) thanks for your work. And GL withi this patch.

**Comment by manishjanky** [comment] 2022-08-20 11:39
Please update to `v3.1.3`

**Closed by manishjanky** 2022-08-20 11:39 UTC

**Comment by AAmeriyan** [comment] 2023-07-15 10:07
this problem is not Totally fixed 
clicking on search input closes the drop down in safari mac and Ios
but in Chrome and Mozilla Firefox its ok
